pipeline {
    agent any
    environment {
        DOCKER_REGISTRY = "ir.arv.cx"
        DOCKER_IMAGE_NAME = "${DOCKER_REGISTRY}/yohanes842/easybill-frontend"
        EASYBILL_VERSION = readJSON(file: '../package.json')['version']
    }
    stages {
        stage("Project and build information") {
            steps {
                script {
                    echo "== Easybill Frontend =="
                    echo "Project version: ${env.EASYBILL_VERSION}"
                    echo "Branch: ${env.BRANCH_NAME}"
                    echo "Building ${DOCKER_IMAGE_NAME}"
                }
            }
        }
        stage("Build image") {
            steps {
                script {
                    image = docker.build("${DOCKER_IMAGE_NAME}:${env.BUILD_ID}")
                }
            }
        }
        stage("Push image") {
            steps {
                script {
                    docker.withRegistry("https://${env.DOCKER_REGISTRY}", "private-image-registry") {
                        if (env.BRANCH_NAME == "master"){
                            image.push("${EASYBILL_VERSION}")
                            image.push("latest")
                        } else if (env.BRANCH_NAME == "dev") {
                            image.push("dev-${EASYBILL_VERSION}")
                            image.push("dev-latest")
                        } else {
                            def sanitizeBranchName = env.BRANCH_NAME.replace("feat/", "")
                            image.push("${sanitizeBranchName}-${EASYBILL_VERSION}")
                            image.push("${sanitizeBranchName}-latest")
                        }
                    }
                }
            }
        }
    }
}